git hooks updated

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,23 +1,53 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
-echo "🚨 Checking commit message..."
+echo "Checking commit message..."
 message="$(cat $1)"
-requiredPattern="^(add|cut|fix|bump|make|start|stop|refactor|reformat|optimise|document|merge|configured) .*$"
-if ! [[ $message =~ $requiredPattern ]];
-then
-  echo "-"
-  echo "-"
-  echo "-"
+
+#requiredPattern="^(add|cut|fix|bump|make|start|stop|refactor|reformat|optimise|document|merge|configured) .*$"
+#if ! [[ $message =~ $requiredPattern ]];
+#then
+#  echo "-"
+#  echo "-"
+#  echo "-"
+#  echo "🚨 Wrong commit message! 😕"
+#  echo "The commit message must have this format:"
+#  echo "<verb in imperative mood> <what was done>"
+#  echo "Allowed verbs in imperative mood: add, cut, fix, bump, make, start, stop, refactor, reformat, optimise, document, merge"
+#  echo "Example: add login button"
+#  echo "-"
+#  echo "Your commit message was:"
+#  echo $message
+#  echo "-"
+#  echo "For more information, check script in .husky/commit-msg"
+#  echo "-"
+#  exit 1
+#fi
+
+
+# Check if the string has at least 9 characters
+if [ ${#message} -lt 9 ]; then
   echo "🚨 Wrong commit message! 😕"
-  echo "The commit message must have this format:"
-  echo "<verb in imperative mood> <what was done>"
-  echo "Allowed verbs in imperative mood: add, cut, fix, bump, make, start, stop, refactor, reformat, optimise, document, merge"
-  echo "Example: add login button"
-  echo "-"
+  echo "Error: Commit message should have at least 9 characters."
   echo "Your commit message was:"
   echo $message
   echo "-"
   echo "For more information, check script in .husky/commit-msg"
-  echo "-"
   exit 1
 fi
+
+# Check if the string contains 2 words
+wordCount=$(echo "$message" | wc -w)
+echo "wordCount: $wordCount"
+if [ $wordCount -lt 2 ]; then
+  echo "🚨 Wrong commit message! 😕"
+  echo "Error: Commit message should contain at least 2 words."
+  echo "Your commit message was:"
+  echo $message
+  echo "-"
+  echo "For more information, check script in .husky/commit-msg"
+  exit 1
+fi
+
+echo "✅ Commit message is valid!"
+
+echo "✅ commit-msg hook finished successfully"
